In [167]:
import pandas as pd
import json

df = pd.read_csv('smartphones - smartphones.csv')

In [168]:
print(df.shape)

(1020, 11)

In [169]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB
None

In [170]:
print(df.isnull().sum())

model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [171]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [172]:
df.columns = df.columns.str.strip().str.lower()

df['price'] = df['price'].str.replace('₹', '').str.replace(',', '').astype(float)

df['rating'] = df['rating'].fillna(df['rating'].mean())
df['os'] = df['os'].fillna('Unknown')
df['card'] = df['card'].fillna('Not Specified')

In [173]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999.0,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989.0,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499.0,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999.0,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999.0,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [174]:
df.drop_duplicates(inplace=True)

In [175]:
def extract_brand(model_name):
    return str(model_name).split(' ')[0]

df['brand'] = df['model'].apply(extract_brand)

In [176]:
def extract_ram(ram_string):
    try:
        parts = str(ram_string).split('GB')
        return int(parts[0].strip())
    except:
        return 0

df['ram_gb'] = df['ram'].apply(extract_ram)

In [177]:
def extract_battery(battery_string):
    try:
        parts = str(battery_string).split('mAh')
        return int(parts[0].strip())
    except:
        return 0

df['battery_mah'] = df['battery'].apply(extract_battery)

In [178]:
def categorize_price(price):
    if price < 15000:
        return 'Budget'
    elif price <= 40000:
        return 'Mid-Range'
    else:
        return 'Premium'

df['price_segment'] = df['price'].apply(categorize_price)

In [179]:
df[['model', 'brand', 'ram_gb', 'battery_mah', 'price_segment']].head()

                       model     brand  ram_gb  battery_mah price_segment
0              OnePlus 11 5G   OnePlus      12         5000       Premium
1  OnePlus Nord CE 2 Lite 5G   OnePlus       6         5000     Mid-Range
2      Samsung Galaxy A14 5G   Samsung       4         5000     Mid-Range
3       Motorola Moto G62 5G  Motorola       6         5000        Budget
4         Realme 10 Pro Plus    Realme       6         5000     Mid-Range

In [217]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os,brand,ram_gb,battery_mah,price_segment
0,OnePlus 11 5G,54999.0,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,OnePlus,12,5000,Premium
1,OnePlus Nord CE 2 Lite 5G,19989.0,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,OnePlus,6,5000,Mid-Range
2,Samsung Galaxy A14 5G,16499.0,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13,Samsung,4,5000,Mid-Range
3,Motorola Moto G62 5G,14999.0,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,Motorola,6,5000,Budget
4,Realme 10 Pro Plus,24999.0,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13,Realme,6,5000,Mid-Range

In [180]:
total_price = df['price'].sum()
avg_rating = df['rating'].mean()
unique_brands = df['brand'].nunique()

In [221]:
avg_price_brand = df.groupby('brand')['price'].mean().sort_values(ascending=False).head(10).reset_index()

In [223]:
brand_count = df.groupby('brand')['model'].count().sort_values(ascending=False).reset_index()

In [225]:
top_rated_phones = df.sort_values(by=['rating', 'price'], ascending=[False, True]).head(10)[['model', 'price', 'rating']]

In [227]:
avg_battery_segment = df.groupby('price_segment')['battery_mah'].mean().reset_index()

Unique Brands: 56
Average Phone Rating: 78.50

In [185]:
kpi_summary = {
    "TOTAL_PRICE": float(total_price),
    "AVERAGE_RATING": float(avg_rating),
    "TOTAL_UNIQUE_BRANDS": int(unique_brands)
}

In [186]:
with open("smartphone_kpi_summary.json", "w") as f:
    json.dump(kpi_summary, f, indent=4)

In [187]:
avg_price_brand.to_json("avg_price_by_brand.json", orient="records", indent=4)
brand_count.to_json("models_per_brand.json", orient="records", indent=4)
top_rated_phones.to_json("top_rated_smartphones.json", orient="records", indent=4)

In [188]:
df.to_json("smartphones_cleaned.json", orient="records", indent=4, date_format="iso")