In [53]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("messy_sales - Sheet1.csv")
df.head(10)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,January 15 2024,north,tablet,electronics,32,USD 858,########,10%
1,1/30/2024,north,Tablet,Electronics,72,$833.83,########,15 percent
2,2/13/2024,EAST,laptop,ELEC,NaN,489.12,NaN,0.08
3,4/28/2024,West,Laptop,gadget,thirty,$733.46,########,0.1
4,2/18/2024,EAST,Phone,ELEC,47,USD 373,"40,920",0.1
5,April 03 2024,South,laptop,Gadgets,twenty,670.28,3103,8 percent
6,1/28/2024,north,tablet,electronics,thirty,758.58,"37,789",8 percent
7,March 15 2024,West,Tablet,Gadgets,47,$241.65,"11,484",12%
8,January 09 2024,West,Phone,gadget,thirty,USD 796,"18,486",8 percent
9,2/7/2024,West,laptop,Gadgets,thirty,$996.92,"20,558",0.08

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               200 non-null    object
 1   Region             200 non-null    object
 2   Product            200 non-null    object
 3   Category           200 non-null    object
 4   Units Sold         196 non-null    object
 5   Unit Price         200 non-null    object
 6   Total Sales        197 non-null    object
 7   Profit Margin (%)  200 non-null    object
dtypes: object(8)
memory usage: 12.6+ KB

In [56]:
df.isnull().sum()

Date                 0
Region               0
Product              0
Category             0
Units Sold           4
Unit Price           0
Total Sales          3
Profit Margin (%)    0
dtype: int64

In [57]:

df["Units Sold"] = pd.to_numeric(df["Units Sold"], errors = "coerce")
df["Total Sales"] = pd.to_numeric(df["Total Sales"], errors = "coerce")

In [58]:
df["Units Sold"] = df["Units Sold"].fillna(df["Units Sold"].mean()).round(2)
df["Total Sales"] = df["Units Sold"].fillna(df["Total Sales"].mean()).round(2)

In [59]:
df.columns = df.columns.str.strip()
df.head(10)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,January 15 2024,north,tablet,electronics,32.00,USD 858,32.00,10%
1,1/30/2024,north,Tablet,Electronics,72.00,$833.83,72.00,15 percent
2,2/13/2024,EAST,laptop,ELEC,52.31,489.12,52.31,0.08
3,4/28/2024,West,Laptop,gadget,52.31,$733.46,52.31,0.1
4,2/18/2024,EAST,Phone,ELEC,47.00,USD 373,47.00,0.1
5,April 03 2024,South,laptop,Gadgets,52.31,670.28,52.31,8 percent
6,1/28/2024,north,tablet,electronics,52.31,758.58,52.31,8 percent
7,March 15 2024,West,Tablet,Gadgets,47.00,$241.65,47.00,12%
8,January 09 2024,West,Phone,gadget,52.31,USD 796,52.31,8 percent
9,2/7/2024,West,laptop,Gadgets,52.31,$996.92,52.31,0.08

In [60]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')
df.head(10)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,2024-01-15,north,tablet,electronics,32.00,USD 858,32.00,10%
1,2024-01-30,north,Tablet,Electronics,72.00,$833.83,72.00,15 percent
2,2024-02-13,EAST,laptop,ELEC,52.31,489.12,52.31,0.08
3,2024-04-28,West,Laptop,gadget,52.31,$733.46,52.31,0.1
4,2024-02-18,EAST,Phone,ELEC,47.00,USD 373,47.00,0.1
5,2024-04-03,South,laptop,Gadgets,52.31,670.28,52.31,8 percent
6,2024-01-28,north,tablet,electronics,52.31,758.58,52.31,8 percent
7,2024-03-15,West,Tablet,Gadgets,47.00,$241.65,47.00,12%
8,2024-01-09,West,Phone,gadget,52.31,USD 796,52.31,8 percent
9,2024-02-07,West,laptop,Gadgets,52.31,$996.92,52.31,0.08

In [61]:
for col in ["Region","Product","Category"]:
    df[col] = df[col].str.strip().str.title()

In [62]:
df.head(10)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,2024-01-15,North,Tablet,Electronics,32.00,USD 858,32.00,10%
1,2024-01-30,North,Tablet,Electronics,72.00,$833.83,72.00,15 percent
2,2024-02-13,East,Laptop,Elec,52.31,489.12,52.31,0.08
3,2024-04-28,West,Laptop,Gadget,52.31,$733.46,52.31,0.1
4,2024-02-18,East,Phone,Elec,47.00,USD 373,47.00,0.1
5,2024-04-03,South,Laptop,Gadgets,52.31,670.28,52.31,8 percent
6,2024-01-28,North,Tablet,Electronics,52.31,758.58,52.31,8 percent
7,2024-03-15,West,Tablet,Gadgets,47.00,$241.65,47.00,12%
8,2024-01-09,West,Phone,Gadget,52.31,USD 796,52.31,8 percent
9,2024-02-07,West,Laptop,Gadgets,52.31,$996.92,52.31,0.08

In [63]:
for col in ["Unit Price","Total Sales"]:
    df[col] = df[col].astype(str)
    df[col] = (df[col].str.replace("[$,USD]","",regex=True).str.strip())
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [64]:
df["Profit Margin (%)"] = ( df["Profit Margin (%)"].astype(str).str.replace("%","",regex=True).str.replace("percent","",regex = True).astype(float))
df["Profit Margin (%)"] = np.where(df["Profit Margin (%)"]<1,df["Profit Margin (%)"]*100,df["Profit Margin (%)"])

In [65]:
df_cleaned = df.dropna(subset=["Date","Total Sales","Region"])

In [66]:
df.head(10)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,2024-01-15,North,Tablet,Electronics,32.00,858.00,32.00,10.0
1,2024-01-30,North,Tablet,Electronics,72.00,833.83,72.00,15.0
2,2024-02-13,East,Laptop,Elec,52.31,489.12,52.31,8.0
3,2024-04-28,West,Laptop,Gadget,52.31,733.46,52.31,10.0
4,2024-02-18,East,Phone,Elec,47.00,373.00,47.00,10.0
5,2024-04-03,South,Laptop,Gadgets,52.31,670.28,52.31,8.0
6,2024-01-28,North,Tablet,Electronics,52.31,758.58,52.31,8.0
7,2024-03-15,West,Tablet,Gadgets,47.00,241.65,47.00,12.0
8,2024-01-09,West,Phone,Gadget,52.31,796.00,52.31,8.0
9,2024-02-07,West,Laptop,Gadgets,52.31,996.92,52.31,8.0

In [67]:
df.loc[df['Category'].str.startswith('E'), 'Category'] = "Electronics"

df.loc[df['Category'].str.startswith('G'), 'Category'] = "Gadgets"

In [ ]:
df.head(5)

,Date,Region,Product,Category,Units Sold,Unit Price,Total Sales,Profit Margin (%)
0,2024-01-15,North,Tablet,Electronics,32.00,858.00,32.00,10.0
1,2024-01-30,North,Tablet,Electronics,72.00,833.83,72.00,15.0
2,2024-02-13,East,Laptop,Electronics,52.31,489.12,52.31,8.0
3,2024-04-28,West,Laptop,Gadgets,52.31,733.46,52.31,10.0
4,2024-02-18,East,Phone,Electronics,47.00,373.00,47.00,10.0